add cynthia
lesterrry/snootberg pull request #2
Opened 2024-12-06 14:04 UTC by MariaIgnatyeva

2024-12-06 14:06 UTC, MariaIgnatyeva commented
my staff: https://staff.yandex-team.ru/ignatjevamash
@lesterrry please approve

2024-12-06 21:47 UTC, lesterrry commented
> my staff: https://staff.yandex-team.ru/ignatjevamash @lesterrry please approve

привет, сожми, пожалуйста, картинки в соответствии с [CONTRIBUTING.md](https://github.com/lesterrry/snootberg/CONTRIBUTING.md)

2024-12-06 21:57 UTC, lesterrry requested changes
привет! сожми, пожалуйста, картинки в соответствии с [CONTRIBUTING.md](https://github.com/lesterrry/snootberg/blob/master/CONTRIBUTING.md)

2024-12-09 11:37 UTC, MariaIgnatyeva commented
@lesterrry done

2024-12-09 11:39 UTC, lesterrry approved these changes

2024-12-09 11:40 UTC, merged